(function() {var implementors = {};
implementors["editor"] = [{"text":"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/default/trait.Default.html\" title=\"trait core::default::Default\">Default</a> for <a class=\"struct\" href=\"editor/struct.Editor.html\" title=\"struct editor::Editor\">Editor</a>","synthetic":false,"types":["editor::Editor"]}];
implementors["graphics"] = [{"text":"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/default/trait.Default.html\" title=\"trait core::default::Default\">Default</a> for <a class=\"struct\" href=\"graphics/struct.WinitState.html\" title=\"struct graphics::WinitState\">WinitState</a>","synthetic":false,"types":["graphics::WinitState"]}];
implementors["notedata"] = [{"text":"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/default/trait.Default.html\" title=\"trait core::default::Default\">Default</a> for <a class=\"struct\" href=\"notedata/struct.ChartMetadata.html\" title=\"struct notedata::ChartMetadata\">ChartMetadata</a>","synthetic":false,"types":["notedata::ChartMetadata"]},{"text":"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/default/trait.Default.html\" title=\"trait core::default::Default\">Default</a> for <a class=\"struct\" href=\"notedata/struct.StructureData.html\" title=\"struct notedata::StructureData\">StructureData</a>","synthetic":false,"types":["notedata::StructureData"]},{"text":"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/default/trait.Default.html\" title=\"trait core::default::Default\">Default</a> for <a class=\"struct\" href=\"notedata/struct.NoteData.html\" title=\"struct notedata::NoteData\">NoteData</a>","synthetic":false,"types":["notedata::NoteData"]}];
implementors["rustmania"] = [{"text":"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/default/trait.Default.html\" title=\"trait core::default::Default\">Default</a> for <a class=\"struct\" href=\"rustmania/struct.SongOptions.html\" title=\"struct rustmania::SongOptions\">SongOptions</a>","synthetic":false,"types":["rustmania::SongOptions"]}];

            if (window.register_implementors) {
                window.register_implementors(implementors);
            } else {
                window.pending_implementors = implementors;
            }
        })()