(function() {var implementors = {};
implementors["notedata"] = [{"text":"impl&lt;T:&nbsp;<a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Copy.html\" title=\"trait core::marker::Copy\">Copy</a>&gt; <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Copy.html\" title=\"trait core::marker::Copy\">Copy</a> for <a class=\"struct\" href=\"notedata/struct.BeatPair.html\" title=\"struct notedata::BeatPair\">BeatPair</a>&lt;T&gt;","synthetic":false,"types":["notedata::BeatPair"]},{"text":"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Copy.html\" title=\"trait core::marker::Copy\">Copy</a> for <a class=\"enum\" href=\"notedata/enum.NoteType.html\" title=\"enum notedata::NoteType\">NoteType</a>","synthetic":false,"types":["notedata::NoteType"]},{"text":"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Copy.html\" title=\"trait core::marker::Copy\">Copy</a> for <a class=\"enum\" href=\"notedata/enum.DisplayBpm.html\" title=\"enum notedata::DisplayBpm\">DisplayBpm</a>","synthetic":false,"types":["notedata::DisplayBpm"]},{"text":"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Copy.html\" title=\"trait core::marker::Copy\">Copy</a> for <a class=\"struct\" href=\"notedata/struct.Note.html\" title=\"struct notedata::Note\">Note</a>","synthetic":false,"types":["notedata::Note"]}];
implementors["rustmania"] = [{"text":"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Copy.html\" title=\"trait core::marker::Copy\">Copy</a> for <a class=\"struct\" href=\"rustmania/player_config/struct.PlayerOptions.html\" title=\"struct rustmania::player_config::PlayerOptions\">PlayerOptions</a>","synthetic":false,"types":["rustmania::player_config::PlayerOptions"]},{"text":"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Copy.html\" title=\"trait core::marker::Copy\">Copy</a> for <a class=\"enum\" href=\"rustmania/screen/enum.ResourceType.html\" title=\"enum rustmania::screen::ResourceType\">ResourceType</a>","synthetic":false,"types":["rustmania::screen::ResourceType"]},{"text":"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Copy.html\" title=\"trait core::marker::Copy\">Copy</a> for <a class=\"struct\" href=\"rustmania/screen/struct.ScriptMap.html\" title=\"struct rustmania::screen::ScriptMap\">ScriptMap</a>","synthetic":false,"types":["rustmania::screen::ScriptMap"]},{"text":"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Copy.html\" title=\"trait core::marker::Copy\">Copy</a> for <a class=\"struct\" href=\"rustmania/screen/struct.ElementMap.html\" title=\"struct rustmania::screen::ElementMap\">ElementMap</a>","synthetic":false,"types":["rustmania::screen::ElementMap"]},{"text":"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Copy.html\" title=\"trait core::marker::Copy\">Copy</a> for <a class=\"enum\" href=\"rustmania/screen/enum.ResourceMap.html\" title=\"enum rustmania::screen::ResourceMap\">ResourceMap</a>","synthetic":false,"types":["rustmania::screen::ResourceMap"]},{"text":"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Copy.html\" title=\"trait core::marker::Copy\">Copy</a> for <a class=\"struct\" href=\"rustmania/timingdata/struct.GameplayInfo.html\" title=\"struct rustmania::timingdata::GameplayInfo\">GameplayInfo</a>","synthetic":false,"types":["rustmania::timingdata::GameplayInfo"]},{"text":"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Copy.html\" title=\"trait core::marker::Copy\">Copy</a> for <a class=\"struct\" href=\"rustmania/timingdata/struct.CalcInfo.html\" title=\"struct rustmania::timingdata::CalcInfo\">CalcInfo</a>","synthetic":false,"types":["rustmania::timingdata::CalcInfo"]},{"text":"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Copy.html\" title=\"trait core::marker::Copy\">Copy</a> for <a class=\"enum\" href=\"rustmania/timingdata/enum.Judgement.html\" title=\"enum rustmania::timingdata::Judgement\">Judgement</a>","synthetic":false,"types":["rustmania::timingdata::Judgement"]}];

            if (window.register_implementors) {
                window.register_implementors(implementors);
            } else {
                window.pending_implementors = implementors;
            }
        })()