(function() {var implementors = {};
implementors["notedata"] = [{"text":"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/convert/trait.From.html\" title=\"trait core::convert::From\">From</a>&lt;<a class=\"struct\" href=\"https://doc.rust-lang.org/nightly/std/io/error/struct.Error.html\" title=\"struct std::io::error::Error\">Error</a>&gt; for <a class=\"enum\" href=\"notedata/enum.ParseError.html\" title=\"enum notedata::ParseError\">ParseError</a>","synthetic":false,"types":["notedata::error::ParseError"]},{"text":"impl&lt;'_&gt; <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/convert/trait.From.html\" title=\"trait core::convert::From\">From</a>&lt;Err&lt;<a class=\"primitive\" href=\"https://doc.rust-lang.org/nightly/std/primitive.tuple.html\">(</a>&amp;'_ <a class=\"primitive\" href=\"https://doc.rust-lang.org/nightly/std/primitive.str.html\">str</a>, ErrorKind<a class=\"primitive\" href=\"https://doc.rust-lang.org/nightly/std/primitive.tuple.html\">)</a>&gt;&gt; for <a class=\"enum\" href=\"notedata/enum.ParseError.html\" title=\"enum notedata::ParseError\">ParseError</a>","synthetic":false,"types":["notedata::error::ParseError"]}];
implementors["rustmania"] = [{"text":"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/convert/trait.From.html\" title=\"trait core::convert::From\">From</a>&lt;<a class=\"struct\" href=\"rustmania/timingdata/struct.TimingColumn.html\" title=\"struct rustmania::timingdata::TimingColumn\">TimingColumn</a>&lt;<a class=\"struct\" href=\"rustmania/timingdata/struct.GameplayInfo.html\" title=\"struct rustmania::timingdata::GameplayInfo\">GameplayInfo</a>&gt;&gt; for <a class=\"struct\" href=\"rustmania/notefield/struct.ColumnInfo.html\" title=\"struct rustmania::notefield::ColumnInfo\">ColumnInfo</a>","synthetic":false,"types":["rustmania::notefield::ColumnInfo"]}];

            if (window.register_implementors) {
                window.register_implementors(implementors);
            } else {
                window.pending_implementors = implementors;
            }
        })()