(function() {var implementors = {};
implementors["graphics"] = [{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/fmt/trait.Debug.html\" title=\"trait core::fmt::Debug\">Debug</a> for <a class=\"struct\" href=\"graphics/struct.WinitState.html\" title=\"struct graphics::WinitState\">WinitState</a>",synthetic:false,types:["graphics::WinitState"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/fmt/trait.Debug.html\" title=\"trait core::fmt::Debug\">Debug</a> for <a class=\"struct\" href=\"graphics/struct.Context.html\" title=\"struct graphics::Context\">Context</a>",synthetic:false,types:["graphics::Context"]},];
implementors["notedata"] = [{text:"impl&lt;T:&nbsp;<a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/fmt/trait.Debug.html\" title=\"trait core::fmt::Debug\">Debug</a>&gt; <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/fmt/trait.Debug.html\" title=\"trait core::fmt::Debug\">Debug</a> for <a class=\"struct\" href=\"notedata/struct.BeatPair.html\" title=\"struct notedata::BeatPair\">BeatPair</a>&lt;T&gt;",synthetic:false,types:["notedata::BeatPair"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/fmt/trait.Debug.html\" title=\"trait core::fmt::Debug\">Debug</a> for <a class=\"enum\" href=\"notedata/enum.NoteType.html\" title=\"enum notedata::NoteType\">NoteType</a>",synthetic:false,types:["notedata::NoteType"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/fmt/trait.Debug.html\" title=\"trait core::fmt::Debug\">Debug</a> for <a class=\"enum\" href=\"notedata/enum.DisplayBpm.html\" title=\"enum notedata::DisplayBpm\">DisplayBpm</a>",synthetic:false,types:["notedata::DisplayBpm"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/fmt/trait.Debug.html\" title=\"trait core::fmt::Debug\">Debug</a> for <a class=\"struct\" href=\"notedata/struct.Note.html\" title=\"struct notedata::Note\">Note</a>",synthetic:false,types:["notedata::Note"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/fmt/trait.Debug.html\" title=\"trait core::fmt::Debug\">Debug</a> for <a class=\"struct\" href=\"notedata/struct.ChartMetadata.html\" title=\"struct notedata::ChartMetadata\">ChartMetadata</a>",synthetic:false,types:["notedata::ChartMetadata"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/fmt/trait.Debug.html\" title=\"trait core::fmt::Debug\">Debug</a> for <a class=\"struct\" href=\"notedata/struct.NoteData.html\" title=\"struct notedata::NoteData\">NoteData</a>",synthetic:false,types:["notedata::NoteData"]},];

            if (window.register_implementors) {
                window.register_implementors(implementors);
            } else {
                window.pending_implementors = implementors;
            }
        })()